import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} bg-gray-900 text-black`}>
        <div>
          <header className="bg-gold text-black shadow-md">
            <div className="container mx-auto p-4 flex justify-between items-center">
              <div className="logo text-3xl font-bold">
                <img src="/logo.png" className="h-24 w-auto"></img>
              </div>
              <nav>
                <ul className="flex space-x-8">
                  <li>
                    <a href="#services" className="text-lg hover:text-orange-500">Usluge</a>
                  </li>
                  <li>
                    <a href="#projects" className="text-lg hover:text-orange-500">Projekti</a>
                  </li>
                  <li>
                    <a href="#about" className="text-lg hover:text-orange-500">O nama</a>
                  </li>
                  <li>
                    <a href="#contact" className="text-lg hover:text-orange-500">Kontakt</a>
                  </li>
                </ul>
              </nav>
            </div>
          </header>
          <main>{children}</main>
          <footer className="bg-gold text-black py-6">
            <div className="container mx-auto text-center">
              <p>&copy; 2025, WEKAS d.o.o, All rights reserved.</p>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
